apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-conf-info
data:
  config: |
    [default]
    role_arn = {{ .Values.aws.role }}
    external_id = 1234
    source_profile = default
    region = us-east-1
