apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    app.gitlab.com/env: {{ .Values.gitlab.env }}
    app.gitlab.com/app: {{ .Values.gitlab.app }}
  name: {{ .Release.Name }}
  labels:
{{ include "hasura.labels" . | indent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "hasura.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      annotations:
        rollme: {{ randAlphaNum 5 | quote }}
        app.gitlab.com/env: {{ .Values.gitlab.env }}
        app.gitlab.com/app: {{ .Values.gitlab.app }}
      labels:
        app.kubernetes.io/name: {{ include "hasura.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ template "hasura.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ include "hasura.fullname" . }}
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: HASURA_GRAPHQL_DATABASE_URL
              valueFrom:
                secretKeyRef:
                  key: HASURA_GRAPHQL_DATABASE_URL
                  name: hasura-secret
            - name: HASURA_GRAPHQL_ADMIN_SECRET
              valueFrom:
                secretKeyRef:
                  key: HASURA_GRAPHQL_ADMIN_SECRET
                  name: hasura-secret
            - name: HASURA_GRAPHQL_ENABLE_CONSOLE
              value: "true"
          ports:
            - name: hasura
              containerPort: {{ .Values.service.porthasura }}
              protgsocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}  

      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
