apiVersion: v1
kind: Secret
metadata:
  name: hasura-secret
  labels:
    app: {{ template "hasura.name" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
type: Opaque
data:
  HASURA_GRAPHQL_DATABASE_URL:  {{ .Values.cred.HASURA_GRAPHQL_DATABASE_URL }}
  HASURA_GRAPHQL_ADMIN_SECRET: {{ .Values.cred.HASURA_GRAPHQL_ADMIN_SECRET }}