{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "hasura.serviceAccountName" . }}
  labels:
{{ include "hasura.labels" . | indent 4 }}
{{- end -}}
