apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  labels:
{{ include "hasura.labels" . | indent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 80
      targetPort: {{ .Values.service.porthasura }}
      protocol: TCP
      name: porthasura
  selector:
    app.kubernetes.io/name: {{ include "hasura.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
