{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "apollo.serviceAccountName" . }}
  labels:
{{ include "apollo.labels" . | indent 4 }}
{{- end -}}
