apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  labels:
{{ include "apollo.labels" . | indent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 80
      targetPort: {{ .Values.service.portapollo }}
      protocol: TCP
      name: portapollo
  selector:
    app.kubernetes.io/name: {{ include "apollo.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
